

#services = 1 container:
        #port:
            #-HOST:CONTAINER

# docker-compose config : pour détailler la config

# version : specify the version of docker-compose. old version don't have some options.
version: "3.5"




networks:
    Inception:
        # name: Inception


# VOLUME
#   driver: specify local volume
#   drivers_opts: option for mount volume (man mount)
#       o: bind : lier/monter le volume d'un repertoire deja existant
#       device = absolute_path of volume

volumes:
    WordPress_volume:
        name: WordPress_volume
        driver: local
        driver_opts:
            o: bind
            type: bind
            device: /home/user42/data/wordpress

    db_volume:
        name: db_volume
        driver: local
        driver_opts:
            o: bind
            type: volume
            device: /home/user42/data/db


# list of all services : 
services:


    nginx:
        container_name: nginx
        image: nginx
        build: ./requirements/nginx/
        depends_on:
            - wordpress
        env_file: .env
        extra_hosts:
            - ${DOMAIN_NAME}:127.0.0.1
        ports:
            - 443:443
        restart: on-failure
        volumes:
            - WordPress_volume:/var/www/wordpress
        networks:
            - Inception
    
            
    wordpress:
        container_name: wordpress
        image: wordpress
        build: ./requirements/wordpress/
        depends_on:
            - mariadb
        # ports:
        env_file: .env
        restart: on-failure
        volumes:
            - WordPress_volume:/var/www/wordpress
        networks:
            - Inception
        
        
    mariadb:
        container_name: mariadb
        image: mariadb
        build: ./requirements/mariadb
        restart: on-failure
        env_file: .env
        volumes:
            - db_volume:/var/lib/mysql
        networks:
            - Inception

        