# CTRL MAJ P  

#services = 1 container:

services:
    nginx:
        container_name: nginx
        build: ./srcs/nginx/
        ports:
            - "443:443"
        restart: always

    wordpress:
        container_name: wordpress
        build: ./srcs/wordpress/
        restart: always

    mariadb:
        container_name: mariadb
        build: ./srcs/mariadb
        restart: always